### ISSUE TITLE
compatibility with Dialogue UI

### ISSUE THREAD

**Issue by rml9ty** [p3lim-wow/InteractiveWormholes#70] opened 2024-07-25 21:33 UTC
I would love if this was compatible with https://legacy.curseforge.com/wow/addons/dialogueui , meaning the dialog/popup shows for only a split second and you can't choose anything.

**Comment by p3lim** [comment] 2024-07-25 21:37
Duplicate of #68.

**Closed by p3lim** 2024-07-25 21:37 UTC
Labels: enhancement
