### ISSUE TITLE
Dark Iron Dwarf Mole Machine does not function

### ISSUE THREAD

**Issue by jrowles** [p3lim-wow/InteractiveWormholes#16] opened 2019-04-28 22:08 UTC
Version:  80100.12-Release

When I attempt to use the Mole Machine, it just closes the map and nothing happens.  This is a duplicate of #13 but that ticket is closed.

**Comment by p3lim** [comment] 2020-09-26 21:43
I'm unable to reproduce this, not on the live servers nor on the Shadowlands beta with the updates for that.

**Comment by jrowles** [comment] 2020-09-27 01:09
This is still an issue for me on live.  I will try it later with all other addons disabled.

**Comment by jrowles** [comment] 2020-09-28 18:38
I'm still trying to narrow down the conflict.  I created a brand new level 20 DID and it works fine with the same addons enabled as my 120.

**Comment by p3lim** [comment] 2020-09-28 18:57
How many of the locations have you discovered on your 120 character?

**Comment by jrowles** [comment] 2020-09-29 13:35
> How many of the locations have you discovered on your 120 character?

All of them.

**Comment by p3lim** [comment] 2020-09-30 05:31
Alright, I can't guarantee any timeline for a fix, as I don't play alliance at all, but I'll try to look into it since it seems to be related to the amount of known locations.

**Comment by p3lim** [comment] 2020-09-30 05:35
Do you happen to play with a non-english client?

**Comment by jrowles** [comment] 2020-09-30 14:13
> Do you happen to play with a non-english client?

No.  My 120 is a race change, but I doubt that's related.

**Comment by p3lim** [comment] 2020-10-02 15:12
I'll unlock and level a Dark Iron Dwarf once prepatch hits so I can test this out myself, I'd do it on the PTR/beta, but it'd be nice to have all those locations unlocked on a character that doesn't get deleted automatically.

Until then, if you have any experience with addon development (or any others reading this), feel free to try out stuff to help me figure out what's wrong, as I can't see anything from my limited interactions with the racial.

**Comment by p3lim** [comment] 2020-10-04 16:11
Had some spare time this weekend, tested out all the mole machine locations properly, had to make a few changes for it to work.
I'll push some code here soon if you want to test it out. If installing manually, you'll have to download HereBeDragons-2.0 from CurseForge yourself (and you'll get some XML warnings, those are fine).
I might set up alpha builds on GitHub.

**Comment by p3lim** [comment] 2020-10-04 16:50
Alpha build artifact is now available, they can be found by looking at the "Package and create artifact" CI job from the commit:
![image](https://user-images.githubusercontent.com/26496/95021632-68d8a900-0672-11eb-8c74-d4228cff1678.png)

then downloading the artifact from the top-right:
![image](https://user-images.githubusercontent.com/26496/95021641-7beb7900-0672-11eb-8dbf-7654df186347.png)

(Or if you just want to test these specific changes, [here is a direct link to the latest build as of writing this](https://github.com/p3lim-wow/InteractiveWormholes/suites/1286789010/artifacts/20009489))

**Comment by p3lim** [comment] 2020-10-04 16:51
With that you should be able to help test the changes, let me know if anything doesn't work.

**Comment by jrowles** [comment] 2020-10-05 03:04
@p3lim Thank you, I will give it a try and let you know!

**Comment by jrowles** [comment] 2020-10-05 04:22
Unfortunately, this still doesn't work.  It just closes the map instead of teleporting.

**Comment by p3lim** [comment] 2020-10-05 04:29
The continent indices are calculated by their order, and flagged as available if the hidden quest is completed.
Can you disable the addon, talk to the mole machine and take screenshots of the list of continents and all the locations within?

**Comment by jrowles** [comment] 2020-10-05 05:08
It looks like it matches.
![image](https://user-images.githubusercontent.com/14367258/95042245-41e89a00-06a7-11eb-873f-378acf6d293f.png)

**Comment by p3lim** [comment] 2020-10-05 07:14
Also, to verify, have you tested it with just InteractiveWormholes enabled?

**Comment by jrowles** [comment] 2020-10-05 12:53
> Also, to verify, have you tested it with just InteractiveWormholes enabled?

Yes, same issue.

**Comment by jrowles** [comment] 2020-10-05 12:55
I clicked Nethergarde Keep, nothing happened.  I opened the Mole Machine again, briefly saw the gossip menu, then clicked Nethergarde Keep a second time, and it took me to Honor Hold.

**Comment by jrowles** [comment] 2020-10-05 14:11
https://www.youtube.com/watch?v=i-FLys2--_Q

**Comment by p3lim** [comment] 2020-10-05 14:17
Ah, fullscreen map, never tested that.

**Comment by p3lim** [comment] 2020-10-05 14:18
Just to confirm, if the map is not full screen, does it work properly for you?
I will investigate what's making the full screen map break the logic, but atleast now I'm able to replicate what you're seeing.

**Comment by jrowles** [comment] 2020-10-05 14:21
I will let you know shortly (30 minute cooldown) :)

**Comment by p3lim** [comment] 2020-10-05 14:29
>  (30 minute cooldown)

Hence why I wanted to create a proper character on live servers, now I can copy it infinitely on the beta and don't have to wait for the cooldown to test it ;).

**Comment by jrowles** [comment] 2020-10-05 14:33
Alternatively, can you open the map in the smaller mode automatically?

**Comment by p3lim** [comment] 2020-10-05 14:34
I could, but I'd rather fix properly if possible.

**Comment by p3lim** [comment] 2020-10-05 15:22
Try out this one whenever you find the time:
https://github.com/p3lim-wow/InteractiveWormholes/suites/1291141546/artifacts/20132770

This should work with both full screen and normal world map.

**Comment by jrowles** [comment] 2020-10-05 15:47
Success!  Thank you for your time in fixing this issue.

**Comment by p3lim** [comment] 2020-10-05 15:56
And thank you for taking the time to helping me test it.

Fixed with d2d0a2e and 4010b1a.

**Closed by p3lim** 2020-10-05 15:56 UTC
Labels: bug
